require("util")

data:extend(require("prototypes.buy_chest"))
data:extend(require("prototypes.sell_chest"))
data:extend(require("prototypes.gate_control"))
data:extend(require("prototypes.platform"))
data:extend(require("prototypes.teleporter"))
data:extend(require("prototypes.water_pump"))
data:extend(require("prototypes.company_monitor"))
data:extend(require("prototypes.shortcut"))
