require("util")

data:extend(require("prototypes.trading_silo"))
data:extend(require("prototypes.gate_control"))
data:extend(require("prototypes.platform"))
data:extend(require("prototypes.teleporter"))
data:extend(require("prototypes.water_pump"))
data:extend(require("prototypes.supply_belt"))
data:extend(require("prototypes.company_monitor"))
data:extend(require("prototypes.shortcut"))
data:extend(require("prototypes.shape_capture"))
data:extend(require("prototypes.shape_place"))
