-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape corridor
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "corridor",
    hook = "room_gates",
    connection = { position = { x = 0, y = 0 }, side = "west", gap = 0, connector = false },
    clearance_box = { { 2, -2 }, { 25, 2 } },
    tile_layers = {
        {
            name = "otc-platform",
            correct = false,
            tiles = runs.expand {
                { -2, 3, 24 },
                { -1, 1, 25 },
                { 0, 1, 25 },
                { 1, 1, 25 },
                { 2, 3, 24 },
            },
        },
    },
    entities = {
        { name = "otc-platform-wall", position = { 1.5, 1.5 } },
        { name = "otc-platform-wall", position = { 1.5, -0.5 } },
        { name = "otc-platform-wall", position = { 2.5, 1.5 } },
        { name = "otc-platform-wall", position = { 2.5, -0.5 } },
        { name = "otc-platform-wall", position = { 3.5, -1.5 } },
        { name = "otc-platform-wall", position = { 3.5, -0.5 } },
        { name = "otc-platform-wall", position = { 3.5, 1.5 } },
        { name = "otc-platform-wall", position = { 3.5, 2.5 } },
        { name = "otc-platform-wall", position = { 4.5, 2.5 } },
        { name = "otc-platform-wall", position = { 4.5, -1.5 } },
        { name = "otc-platform-wall", position = { 5.5, 2.5 } },
        { name = "otc-platform-wall", position = { 5.5, -1.5 } },
        { name = "otc-platform-wall", position = { 6.5, 2.5 } },
        { name = "otc-platform-wall", position = { 6.5, -1.5 } },
        { name = "otc-platform-wall", position = { 7.5, 2.5 } },
        { name = "otc-platform-wall", position = { 7.5, -1.5 } },
        { name = "otc-platform-wall", position = { 8.5, 2.5 } },
        { name = "otc-platform-wall", position = { 8.5, -1.5 } },
        { name = "otc-platform-wall", position = { 9.5, 2.5 } },
        { name = "otc-platform-wall", position = { 9.5, -1.5 } },
        { name = "otc-platform-wall", position = { 10.5, 2.5 } },
        { name = "otc-platform-wall", position = { 10.5, -1.5 } },
        { name = "otc-platform-wall", position = { 11.5, 2.5 } },
        { name = "otc-platform-wall", position = { 11.5, -1.5 } },
        { name = "otc-platform-wall", position = { 12.5, 2.5 } },
        { name = "otc-platform-wall", position = { 12.5, -1.5 } },
        { name = "otc-platform-wall", position = { 13.5, 2.5 } },
        { name = "otc-platform-wall", position = { 13.5, -1.5 } },
        { name = "otc-platform-wall", position = { 14.5, 2.5 } },
        { name = "otc-platform-wall", position = { 14.5, -1.5 } },
        { name = "otc-platform-wall", position = { 15.5, 2.5 } },
        { name = "otc-platform-wall", position = { 15.5, -1.5 } },
        { name = "otc-platform-wall", position = { 16.5, 2.5 } },
        { name = "otc-platform-wall", position = { 16.5, -1.5 } },
        { name = "otc-platform-wall", position = { 17.5, 2.5 } },
        { name = "otc-platform-wall", position = { 17.5, -1.5 } },
        { name = "otc-platform-wall", position = { 18.5, 2.5 } },
        { name = "otc-platform-wall", position = { 18.5, -1.5 } },
        { name = "otc-platform-wall", position = { 19.5, 2.5 } },
        { name = "otc-platform-wall", position = { 19.5, -1.5 } },
        { name = "otc-platform-wall", position = { 20.5, 2.5 } },
        { name = "otc-platform-wall", position = { 20.5, -1.5 } },
        { name = "otc-platform-wall", position = { 21.5, 2.5 } },
        { name = "otc-platform-wall", position = { 21.5, -1.5 } },
        { name = "otc-platform-wall", position = { 22.5, 2.5 } },
        { name = "otc-platform-wall", position = { 22.5, -1.5 } },
        { name = "otc-platform-wall", position = { 23.5, 2.5 } },
        { name = "otc-platform-wall", position = { 23.5, -1.5 } },
        { name = "otc-platform-wall", position = { 24.5, 2.5 } },
        { name = "otc-platform-wall", position = { 24.5, -1.5 } },
        { name = "otc-platform-wall", position = { 24.5, -0.5 } },
        { name = "otc-platform-wall", position = { 24.5, 1.5 } },
        { name = "otc-platform-wall", position = { 25.5, 1.5 } },
        { name = "otc-platform-wall", position = { 25.5, -0.5 } },
        { name = "gate", position = { 3.5, 0.5 }, role = "gate", side = "west", skip_create = true },
        { name = "gate", position = { 24.5, 0.5 }, role = "gate", side = "east", skip_create = true },
        {
            name = "otc-gate-computer",
            position = { 25.5, 0.5 },
            role = "computer",
            side = "east",
            skip_create = true,
        },
    },
}
