-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape hub
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "hub",
    hook = "room_gates",
    connection = { position = { x = -6, y = 0 }, side = "west", gap = 3, connector = true },
    clearance_box = { { -7, -7 }, { 7, 7 } },
    tile_layers = {
        {
            name = "otc-platform",
            correct = false,
            tiles = runs.expand {
                { -7, -1, 1 },
                { -6, -6, 6 },
                { -5, -6, 6 },
                { -4, -6, 6 },
                { -3, -6, 6 },
                { -2, -6, 6 },
                { -1, -7, 7 },
                { 0, -7, 7 },
                { 1, -7, 7 },
                { 2, -6, 6 },
                { 3, -6, 6 },
                { 4, -6, 6 },
                { 5, -6, 6 },
                { 6, -6, 6 },
                { 7, -1, 1 },
            },
        },
    },
    entities = {
        { name = "otc-platform-wall", position = { -5.5, -5.5 } },
        { name = "otc-platform-wall", position = { -5.5, -4.5 } },
        { name = "otc-platform-wall", position = { -5.5, -3.5 } },
        { name = "otc-platform-wall", position = { -5.5, -2.5 } },
        { name = "otc-platform-wall", position = { -5.5, -1.5 } },
        { name = "otc-platform-wall", position = { -5.5, -0.5 } },
        { name = "otc-platform-wall", position = { -5.5, 1.5 } },
        { name = "otc-platform-wall", position = { -5.5, 2.5 } },
        { name = "otc-platform-wall", position = { -5.5, 3.5 } },
        { name = "otc-platform-wall", position = { -5.5, 4.5 } },
        { name = "otc-platform-wall", position = { -5.5, 5.5 } },
        { name = "otc-platform-wall", position = { -5.5, 6.5 } },
        { name = "otc-platform-wall", position = { 6.5, -5.5 } },
        { name = "otc-platform-wall", position = { 6.5, -4.5 } },
        { name = "otc-platform-wall", position = { 6.5, -3.5 } },
        { name = "otc-platform-wall", position = { 6.5, -2.5 } },
        { name = "otc-platform-wall", position = { 6.5, -1.5 } },
        { name = "otc-platform-wall", position = { 6.5, -0.5 } },
        { name = "otc-platform-wall", position = { 6.5, 1.5 } },
        { name = "otc-platform-wall", position = { 6.5, 2.5 } },
        { name = "otc-platform-wall", position = { 6.5, 3.5 } },
        { name = "otc-platform-wall", position = { 6.5, 4.5 } },
        { name = "otc-platform-wall", position = { 6.5, 5.5 } },
        { name = "otc-platform-wall", position = { 6.5, 6.5 } },
        { name = "otc-platform-wall", position = { -4.5, -5.5 } },
        { name = "otc-platform-wall", position = { -3.5, -5.5 } },
        { name = "otc-platform-wall", position = { -2.5, -5.5 } },
        { name = "otc-platform-wall", position = { -1.5, -5.5 } },
        { name = "otc-platform-wall", position = { -0.5, -5.5 } },
        { name = "otc-platform-wall", position = { 1.5, -5.5 } },
        { name = "otc-platform-wall", position = { 2.5, -5.5 } },
        { name = "otc-platform-wall", position = { 3.5, -5.5 } },
        { name = "otc-platform-wall", position = { 4.5, -5.5 } },
        { name = "otc-platform-wall", position = { 5.5, -5.5 } },
        { name = "otc-platform-wall", position = { -4.5, 6.5 } },
        { name = "otc-platform-wall", position = { -3.5, 6.5 } },
        { name = "otc-platform-wall", position = { -2.5, 6.5 } },
        { name = "otc-platform-wall", position = { -1.5, 6.5 } },
        { name = "otc-platform-wall", position = { -0.5, 6.5 } },
        { name = "otc-platform-wall", position = { 1.5, 6.5 } },
        { name = "otc-platform-wall", position = { 2.5, 6.5 } },
        { name = "otc-platform-wall", position = { 3.5, 6.5 } },
        { name = "otc-platform-wall", position = { 4.5, 6.5 } },
        { name = "otc-platform-wall", position = { 5.5, 6.5 } },
        { name = "otc-platform-wall", position = { 7.5, 1.5 } },
        { name = "otc-platform-wall", position = { 7.5, -0.5 } },
        { name = "otc-platform-wall", position = { -6.5, 1.5 } },
        { name = "otc-platform-wall", position = { -6.5, -0.5 } },
        { name = "otc-platform-wall", position = { 1.5, 7.5 } },
        { name = "otc-platform-wall", position = { -0.5, 7.5 } },
        { name = "otc-platform-wall", position = { 1.5, -6.5 } },
        { name = "otc-platform-wall", position = { -0.5, -6.5 } },
        { name = "gate", position = { 6.5, 0.5 }, role = "gate", side = "east", skip_create = true },
        { name = "otc-gate-computer", position = { 7.5, 0.5 }, role = "computer", side = "east", skip_create = true },
        { name = "gate", position = { -5.5, 0.5 }, role = "gate", side = "west", skip_create = true },
        { name = "gate", position = { 0.5, 6.5 }, role = "gate", side = "north", skip_create = true },
        {
            name = "otc-gate-computer",
            position = { 0.5, 7.5 },
            role = "computer",
            side = "north",
            skip_create = true,
        },
        { name = "gate", position = { 0.5, -5.5 }, role = "gate", side = "south", skip_create = true },
        {
            name = "otc-gate-computer",
            position = { 0.5, -6.5 },
            role = "computer",
            side = "south",
            skip_create = true,
        },
    },
}
