-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape nauvis_mine_iron
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
return {
    format = 1,
    name = "nauvis_mine_iron",
    hook = "stock_belts",
    clearance_box = { { 0, 0 }, { 8, 9 } },
    entities = {
        { name = "substation", position = { 5, 1 } },
        { name = "electric-mining-drill", position = { 2.5, 3.5 }, direction = 4 },
        { name = "transport-belt", position = { 4.5, 4.5 }, direction = 8 },
        { name = "transport-belt", position = { 4.5, 3.5 }, direction = 8 },
        { name = "electric-mining-drill", position = { 6.5, 3.5 }, direction = 12 },
        { name = "transport-belt", position = { 4.5, 6.5 }, direction = 8 },
        { name = "transport-belt", position = { 4.5, 5.5 }, direction = 8 },
        { name = "electric-mining-drill", position = { 2.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 4.5, 8.5 }, direction = 8 },
        { name = "transport-belt", position = { 4.5, 7.5 }, direction = 8 },
        { name = "electric-mining-drill", position = { 6.5, 7.5 }, direction = 12 },
        { name = "otc-intake-belt", position = { 4.5, 9.5 }, direction = 8, role = "intake", belt_type = "input" },
    },
    resources = {
        { name = "iron-ore", position = { 2, 2 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 2 }, amount = 208050 },
        { name = "iron-ore", position = { 3, 2 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 1 }, amount = 208050 },
        { name = "iron-ore", position = { 6, 2 }, amount = 208050 },
        { name = "iron-ore", position = { 5, 2 }, amount = 208050 },
        { name = "iron-ore", position = { 2, 4 }, amount = 208050 },
        { name = "iron-ore", position = { 1, 4 }, amount = 208050 },
        { name = "iron-ore", position = { 2, 3 }, amount = 208050 },
        { name = "iron-ore", position = { 1, 3 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 4 }, amount = 208050 },
        { name = "iron-ore", position = { 3, 4 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 3 }, amount = 208050 },
        { name = "iron-ore", position = { 3, 3 }, amount = 208050 },
        { name = "iron-ore", position = { 6, 4 }, amount = 208050 },
        { name = "iron-ore", position = { 5, 4 }, amount = 208050 },
        { name = "iron-ore", position = { 6, 3 }, amount = 208050 },
        { name = "iron-ore", position = { 5, 3 }, amount = 208050 },
        { name = "iron-ore", position = { 7, 4 }, amount = 208050 },
        { name = "iron-ore", position = { 7, 3 }, amount = 208050 },
        { name = "iron-ore", position = { 0, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 2, 6 }, amount = 208050 },
        { name = "iron-ore", position = { 1, 6 }, amount = 208050 },
        { name = "iron-ore", position = { 2, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 1, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 6 }, amount = 208050 },
        { name = "iron-ore", position = { 3, 6 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 3, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 6, 6 }, amount = 208050 },
        { name = "iron-ore", position = { 5, 6 }, amount = 208050 },
        { name = "iron-ore", position = { 6, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 5, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 7, 6 }, amount = 208050 },
        { name = "iron-ore", position = { 8, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 7, 5 }, amount = 208050 },
        { name = "iron-ore", position = { 2, 8 }, amount = 208050 },
        { name = "iron-ore", position = { 2, 7 }, amount = 208050 },
        { name = "iron-ore", position = { 1, 7 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 8 }, amount = 208050 },
        { name = "iron-ore", position = { 3, 8 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 7 }, amount = 208050 },
        { name = "iron-ore", position = { 3, 7 }, amount = 208050 },
        { name = "iron-ore", position = { 6, 8 }, amount = 208050 },
        { name = "iron-ore", position = { 5, 8 }, amount = 208050 },
        { name = "iron-ore", position = { 6, 7 }, amount = 208050 },
        { name = "iron-ore", position = { 5, 7 }, amount = 208050 },
        { name = "iron-ore", position = { 7, 7 }, amount = 208050 },
        { name = "iron-ore", position = { 4, 9 }, amount = 208050 },
    },
    notes = {
        "The stone mine's footprint with iron ore under it: every mine block is the",
        "same shape, so the district reads as one grid of interchangeable blocks.",
        "Placed, not bought, so it has no connection anchor.",
        "role=intake belts are registered as stock intakes by the hook.",
        "Lays no tiles: the district's grass is the ground under every mine.",
        "No generation of its own: the substation reaches the district's pole line.",
    },
}
