-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape nauvis_production_room
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "nauvis_production_room",
    hook = "nauvis_production_room",
    clearance_box = { { -13, -27 }, { 13, -9 } },
    tile_layers = {
        {
            name = "otc-platform",
            correct = true,
            tiles = runs.expand {
                { -27, -13, 13 },
                { -26, -13, 13 },
                { -25, -13, 13 },
                { -24, -13, 13 },
                { -23, -13, 13 },
                { -22, -13, 13 },
                { -21, -13, 13 },
                { -20, -13, 13 },
                { -19, -13, 13 },
                { -18, -13, 13 },
                { -17, -13, 13 },
                { -16, -13, 13 },
                { -15, -13, 13 },
                { -14, -13, 13 },
                { -13, -13, 13 },
                { -12, -13, 13 },
                { -11, -13, 13 },
                { -10, -13, 13 },
                { -9, -13, 13 },
            },
        },
    },
    entities = {
        { name = "otc-platform-wall", position = { -12.5, -26.5 } },
        { name = "otc-platform-wall", position = { -12.5, -25.5 } },
        { name = "otc-platform-wall", position = { -12.5, -24.5 } },
        { name = "otc-platform-wall", position = { -12.5, -23.5 } },
        { name = "otc-platform-wall", position = { -12.5, -22.5 } },
        { name = "otc-platform-wall", position = { -12.5, -21.5 } },
        { name = "otc-platform-wall", position = { -12.5, -20.5 } },
        { name = "otc-platform-wall", position = { -12.5, -19.5 } },
        { name = "otc-platform-wall", position = { -12.5, -18.5 } },
        { name = "otc-platform-wall", position = { -12.5, -17.5 } },
        { name = "otc-platform-wall", position = { -12.5, -16.5 } },
        { name = "otc-platform-wall", position = { -12.5, -15.5 } },
        { name = "otc-platform-wall", position = { -12.5, -14.5 } },
        { name = "otc-platform-wall", position = { -12.5, -13.5 } },
        { name = "otc-platform-wall", position = { -12.5, -12.5 } },
        { name = "otc-platform-wall", position = { -12.5, -11.5 } },
        { name = "otc-platform-wall", position = { -12.5, -10.5 } },
        { name = "otc-platform-wall", position = { -12.5, -9.5 } },
        { name = "otc-platform-wall", position = { -12.5, -8.5 } },
        { name = "otc-platform-wall", position = { -11.5, -26.5 } },
        { name = "otc-platform-wall", position = { -11.5, -8.5 } },
        { name = "otc-platform-wall", position = { -10.5, -26.5 } },
        { name = "otc-platform-wall", position = { -10.5, -8.5 } },
        { name = "otc-platform-wall", position = { -9.5, -26.5 } },
        { name = "otc-platform-wall", position = { -9.5, -8.5 } },
        { name = "otc-platform-wall", position = { -8.5, -26.5 } },
        { name = "otc-platform-wall", position = { -8.5, -8.5 } },
        { name = "otc-platform-wall", position = { -7.5, -26.5 } },
        { name = "otc-platform-wall", position = { -7.5, -8.5 } },
        { name = "otc-platform-wall", position = { -6.5, -26.5 } },
        { name = "otc-platform-wall", position = { -6.5, -8.5 } },
        { name = "otc-platform-wall", position = { -5.5, -26.5 } },
        { name = "otc-platform-wall", position = { -5.5, -8.5 } },
        { name = "otc-platform-wall", position = { -4.5, -26.5 } },
        { name = "otc-platform-wall", position = { -4.5, -8.5 } },
        { name = "otc-platform-wall", position = { -3.5, -26.5 } },
        { name = "otc-platform-wall", position = { -3.5, -8.5 } },
        { name = "otc-platform-wall", position = { -2.5, -26.5 } },
        { name = "otc-platform-wall", position = { -2.5, -8.5 } },
        { name = "otc-platform-wall", position = { -1.5, -26.5 } },
        { name = "otc-platform-wall", position = { -1.5, -8.5 } },
        { name = "otc-platform-wall", position = { -0.5, -26.5 } },
        { name = "otc-platform-wall", position = { -0.5, -8.5 } },
        { name = "otc-platform-wall", position = { 0.5, -26.5 } },
        { name = "otc-platform-wall", position = { 0.5, -8.5 } },
        { name = "otc-platform-wall", position = { 1.5, -26.5 } },
        { name = "otc-platform-wall", position = { 1.5, -8.5 } },
        { name = "otc-platform-wall", position = { 2.5, -26.5 } },
        { name = "otc-platform-wall", position = { 2.5, -8.5 } },
        { name = "otc-platform-wall", position = { 3.5, -26.5 } },
        { name = "otc-platform-wall", position = { 3.5, -8.5 } },
        { name = "otc-platform-wall", position = { 4.5, -26.5 } },
        { name = "otc-platform-wall", position = { 4.5, -8.5 } },
        { name = "otc-platform-wall", position = { 5.5, -26.5 } },
        { name = "otc-platform-wall", position = { 5.5, -8.5 } },
        { name = "otc-platform-wall", position = { 6.5, -26.5 } },
        { name = "otc-platform-wall", position = { 6.5, -8.5 } },
        { name = "otc-platform-wall", position = { 7.5, -26.5 } },
        { name = "otc-platform-wall", position = { 7.5, -8.5 } },
        { name = "otc-platform-wall", position = { 8.5, -26.5 } },
        { name = "otc-platform-wall", position = { 8.5, -8.5 } },
        { name = "otc-platform-wall", position = { 9.5, -26.5 } },
        { name = "otc-platform-wall", position = { 9.5, -8.5 } },
        { name = "otc-platform-wall", position = { 10.5, -26.5 } },
        { name = "otc-platform-wall", position = { 10.5, -8.5 } },
        { name = "otc-platform-wall", position = { 11.5, -26.5 } },
        { name = "otc-platform-wall", position = { 11.5, -8.5 } },
        { name = "otc-platform-wall", position = { 12.5, -26.5 } },
        { name = "otc-platform-wall", position = { 12.5, -8.5 } },
        { name = "otc-platform-wall", position = { 13.5, -26.5 } },
        { name = "otc-platform-wall", position = { 13.5, -25.5 } },
        { name = "otc-platform-wall", position = { 13.5, -24.5 } },
        { name = "otc-platform-wall", position = { 13.5, -23.5 } },
        { name = "otc-platform-wall", position = { 13.5, -22.5 } },
        { name = "otc-platform-wall", position = { 13.5, -21.5 } },
        { name = "otc-platform-wall", position = { 13.5, -20.5 } },
        { name = "otc-platform-wall", position = { 13.5, -19.5 } },
        { name = "otc-platform-wall", position = { 13.5, -18.5 } },
        { name = "otc-platform-wall", position = { 13.5, -17.5 } },
        { name = "otc-platform-wall", position = { 13.5, -16.5 } },
        { name = "otc-platform-wall", position = { 13.5, -15.5 } },
        { name = "otc-platform-wall", position = { 13.5, -14.5 } },
        { name = "otc-platform-wall", position = { 13.5, -13.5 } },
        { name = "otc-platform-wall", position = { 13.5, -12.5 } },
        { name = "otc-platform-wall", position = { 13.5, -11.5 } },
        { name = "otc-platform-wall", position = { 13.5, -10.5 } },
        { name = "otc-platform-wall", position = { 13.5, -9.5 } },
        { name = "otc-platform-wall", position = { 13.5, -8.5 } },
        { name = "solar-panel", position = { -10.5, -24.5 } },
        { name = "solar-panel", position = { -6.5, -24.5 } },
        { name = "solar-panel", position = { -2.5, -24.5 } },
        { name = "solar-panel", position = { 1.5, -24.5 } },
        { name = "solar-panel", position = { 5.5, -24.5 } },
        { name = "solar-panel", position = { 9.5, -24.5 } },
        { name = "solar-panel", position = { -10.5, -21.5 } },
        { name = "solar-panel", position = { -6.5, -21.5 } },
        { name = "accumulator", position = { -3, -22 } },
        { name = "accumulator", position = { -1, -22 } },
        { name = "accumulator", position = { 1, -22 } },
        { name = "accumulator", position = { 3, -22 } },
        { name = "accumulator", position = { 5, -22 } },
        { name = "accumulator", position = { 7, -22 } },
        { name = "accumulator", position = { 9, -22 } },
        { name = "substation", position = { -9, -18 } },
        { name = "substation", position = { 0, -18 } },
        { name = "substation", position = { 9, -18 } },
        { name = "assembling-machine-1", position = { -3.5, -14.5 }, recipe = "iron-gear-wheel" },
        { name = "assembling-machine-1", position = { 0.5, -14.5 }, recipe = "automation-science-pack" },
        { name = "lab", position = { 0.5, -10.5 }, role = "lab" },
        { name = "otc-supply-belt", position = { -7.5, -14.5 }, direction = 4, belt_type = "output" },
        { name = "transport-belt", position = { -6.5, -14.5 }, direction = 4, role = "supply", item = "iron-plate" },
        { name = "otc-supply-belt", position = { 4.5, -14.5 }, direction = 12, belt_type = "output" },
        {
            name = "transport-belt",
            position = { 3.5, -14.5 },
            direction = 12,
            role = "supply",
            item = "copper-plate",
        },
        { name = "inserter", position = { -5.5, -14.5 }, direction = 12 },
        { name = "inserter", position = { -1.5, -14.5 }, direction = 12 },
        { name = "inserter", position = { 2.5, -14.5 }, direction = 4 },
        { name = "inserter", position = { 0.5, -12.5 }, direction = 0 },
    },
    notes = {
        "Applied at world origin {0, 0}; coordinates are absolute Nauvis positions.",
        "role=supply transport belts are registered against their item by the hook.",
    },
}
