-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape nauvis_starting_room
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "nauvis_starting_room",
    hook = "starting_room",
    clear_area = true,
    clearance_box = { { -6, -6 }, { 6, 6 } },
    tile_layers = {
        {
            name = "otc-platform",
            correct = true,
            tiles = runs.expand {
                { -6, -6, 6 },
                { -5, -6, 6 },
                { -4, -6, 6 },
                { -3, -6, 6 },
                { -2, -6, 6 },
                { -1, -6, 6 },
                { 0, -6, 6 },
                { 1, -6, 6 },
                { 2, -6, 6 },
                { 3, -6, 6 },
                { 4, -6, 6 },
                { 5, -6, 6 },
                { 6, -6, 6 },
            },
        },
    },
    entities = {
        { name = "otc-platform-wall", position = { -5.5, -5.5 } },
        { name = "otc-platform-wall", position = { -5.5, -4.5 } },
        { name = "otc-platform-wall", position = { -5.5, -3.5 } },
        { name = "otc-platform-wall", position = { -5.5, -2.5 } },
        { name = "otc-platform-wall", position = { -5.5, -1.5 } },
        { name = "otc-platform-wall", position = { -5.5, -0.5 } },
        { name = "otc-platform-wall", position = { -5.5, 1.5 } },
        { name = "otc-platform-wall", position = { -5.5, 2.5 } },
        { name = "otc-platform-wall", position = { -5.5, 3.5 } },
        { name = "otc-platform-wall", position = { -5.5, 4.5 } },
        { name = "otc-platform-wall", position = { -5.5, 5.5 } },
        { name = "otc-platform-wall", position = { -5.5, 6.5 } },
        { name = "otc-platform-wall", position = { -4.5, -5.5 } },
        { name = "otc-platform-wall", position = { -4.5, 6.5 } },
        { name = "otc-platform-wall", position = { -3.5, -5.5 } },
        { name = "otc-platform-wall", position = { -3.5, 6.5 } },
        { name = "otc-platform-wall", position = { -2.5, -5.5 } },
        { name = "otc-platform-wall", position = { -2.5, 6.5 } },
        { name = "otc-platform-wall", position = { -1.5, -5.5 } },
        { name = "otc-platform-wall", position = { -1.5, 6.5 } },
        { name = "otc-platform-wall", position = { -0.5, -5.5 } },
        { name = "otc-platform-wall", position = { -0.5, 6.5 } },
        { name = "otc-platform-wall", position = { 0.5, -5.5 } },
        { name = "otc-platform-wall", position = { 1.5, -5.5 } },
        { name = "otc-platform-wall", position = { 1.5, 6.5 } },
        { name = "otc-platform-wall", position = { 2.5, -5.5 } },
        { name = "otc-platform-wall", position = { 2.5, 6.5 } },
        { name = "otc-platform-wall", position = { 3.5, -5.5 } },
        { name = "otc-platform-wall", position = { 3.5, 6.5 } },
        { name = "otc-platform-wall", position = { 4.5, -5.5 } },
        { name = "otc-platform-wall", position = { 4.5, 6.5 } },
        { name = "otc-platform-wall", position = { 5.5, -5.5 } },
        { name = "otc-platform-wall", position = { 5.5, 6.5 } },
        { name = "otc-platform-wall", position = { 6.5, -5.5 } },
        { name = "otc-platform-wall", position = { 6.5, -4.5 } },
        { name = "otc-platform-wall", position = { 6.5, -3.5 } },
        { name = "otc-platform-wall", position = { 6.5, -2.5 } },
        { name = "otc-platform-wall", position = { 6.5, -1.5 } },
        { name = "otc-platform-wall", position = { 6.5, -0.5 } },
        { name = "otc-platform-wall", position = { 6.5, 1.5 } },
        { name = "otc-platform-wall", position = { 6.5, 2.5 } },
        { name = "otc-platform-wall", position = { 6.5, 3.5 } },
        { name = "otc-platform-wall", position = { 6.5, 4.5 } },
        { name = "otc-platform-wall", position = { 6.5, 5.5 } },
        { name = "otc-platform-wall", position = { 6.5, 6.5 } },
        { name = "otc-company-monitor", position = { 4.5, 4.5 }, role = "company_monitor", skip_create = true },
    },
    notes = {
        "Airlock gates and computers are placed by scripts/platform_gates.lua,",
        "not by this definition -- their tiles are left free of walls.",
    },
}
