-- Shape definition. Re-capture in game with: /otc-capture-shape nauvis_lab
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "nauvis_lab",
    hook = "stock_belts",
    -- Same footprint as red_flask_factory, so a slot holds either one.
    clearance_box = { { 0, 0 }, { 21, 13 } },
    tile_layers = {
        {
            name = "refined-concrete",
            correct = true,
            tiles = runs.expand {
                { 0, 0, 21 },
                { 1, 0, 21 },
                { 2, 0, 21 },
                { 3, 0, 21 },
                { 4, 0, 21 },
                { 5, 0, 21 },
                { 6, 0, 21 },
                { 7, 0, 21 },
                { 8, 0, 21 },
                { 9, 0, 21 },
                { 10, 0, 21 },
                { 11, 0, 21 },
                { 12, 0, 21 },
                { 13, 0, 21 },
            },
        },
        {
            name = "refined-hazard-concrete-left",
            correct = true,
            tiles = runs.expand {
                { 0, 0, 21 },
                { 1, 0, 0 },
                { 1, 21, 21 },
                { 2, 0, 0 },
                { 2, 21, 21 },
                { 3, 0, 0 },
                { 3, 21, 21 },
                { 4, 0, 0 },
                { 4, 21, 21 },
                { 5, 0, 0 },
                { 5, 21, 21 },
                { 6, 0, 0 },
                { 6, 21, 21 },
                { 7, 0, 0 },
                { 7, 21, 21 },
                { 8, 0, 0 },
                { 8, 21, 21 },
                { 9, 0, 0 },
                { 9, 21, 21 },
                { 10, 0, 0 },
                { 10, 21, 21 },
                { 11, 0, 0 },
                { 11, 21, 21 },
                { 12, 0, 0 },
                { 12, 21, 21 },
                { 13, 0, 21 },
            },
        },
    },
    entities = {
        { name = "substation", position = { 2, 1 } },
        { name = "substation", position = { 20, 1 } },

        { name = "lab", position = { 3.5, 3.5 } },
        { name = "lab", position = { 6.5, 3.5 } },
        { name = "lab", position = { 9.5, 3.5 } },
        { name = "lab", position = { 12.5, 3.5 } },
        { name = "lab", position = { 15.5, 3.5 } },
        { name = "lab", position = { 18.5, 3.5 } },

        { name = "inserter", position = { 3.5, 5.5 }, direction = 8 },
        { name = "inserter", position = { 6.5, 5.5 }, direction = 8 },
        { name = "inserter", position = { 9.5, 5.5 }, direction = 8 },
        { name = "inserter", position = { 12.5, 5.5 }, direction = 8 },
        { name = "inserter", position = { 15.5, 5.5 }, direction = 8 },
        { name = "inserter", position = { 18.5, 5.5 }, direction = 8 },

        -- Packs come out of stock at the west end, run east past the top row,
        -- turn down at the far wall and come back west past the bottom row.
        -- Whatever the labs did not take goes back into stock at the intake, so
        -- a full belt never strands what it drew.
        {
            name = "otc-supply-belt",
            position = { 2.5, 6.5 },
            direction = 4,
            role = "supply",
            belt_type = "output",
            item = "automation-science-pack",
        },
        { name = "transport-belt", position = { 3.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 4.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 5.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 6.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 7.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 8.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 9.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 10.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 11.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 12.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 13.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 14.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 15.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 16.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 17.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 18.5, 6.5 }, direction = 4 },
        { name = "transport-belt", position = { 19.5, 6.5 }, direction = 8 },

        { name = "transport-belt", position = { 19.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 18.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 17.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 16.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 15.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 14.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 13.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 12.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 11.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 10.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 9.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 8.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 7.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 6.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 5.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 4.5, 7.5 }, direction = 12 },
        { name = "transport-belt", position = { 3.5, 7.5 }, direction = 12 },
        {
            name = "otc-intake-belt",
            position = { 2.5, 7.5 },
            direction = 12,
            role = "intake",
            belt_type = "input",
        },

        { name = "inserter", position = { 3.5, 8.5 }, direction = 0 },
        { name = "inserter", position = { 6.5, 8.5 }, direction = 0 },
        { name = "inserter", position = { 9.5, 8.5 }, direction = 0 },
        { name = "inserter", position = { 12.5, 8.5 }, direction = 0 },
        { name = "inserter", position = { 15.5, 8.5 }, direction = 0 },
        { name = "inserter", position = { 18.5, 8.5 }, direction = 0 },

        { name = "lab", position = { 3.5, 10.5 } },
        { name = "lab", position = { 6.5, 10.5 } },
        { name = "lab", position = { 9.5, 10.5 } },
        { name = "lab", position = { 12.5, 10.5 } },
        { name = "lab", position = { 15.5, 10.5 } },
        { name = "lab", position = { 18.5, 10.5 } },
    },
    notes = {
        "Where Nauvis spends the science packs its factories make: labs are state",
        "property, so this is the only place research happens.",
        "Fixed Nauvis build, not a gate expansion, so it needs no connection anchor.",
        "Inserters point at their pickup: the top row faces south onto the outbound",
        "belt, the bottom row faces north onto the return.",
    },
}
