-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape orbital_station
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "orbital_station",
    hook = "orbital_station",
    clear_area = true,
    connection = { position = { x = -7, y = 0 }, side = "west", gap = 2, connector = true },
    clearance_box = { { -7, -7 }, { 7, 7 } },
    tile_layers = {
        {
            name = "otc-platform",
            correct = true,
            tiles = runs.expand {
                { -7, -7, 7 },
                { -6, -7, 7 },
                { -5, -7, 7 },
                { -4, -7, 7 },
                { -3, -7, 7 },
                { -2, -7, 7 },
                { -1, -7, 7 },
                { 0, -7, 7 },
                { 1, -7, 7 },
                { 2, -7, 7 },
                { 3, -7, 7 },
                { 4, -7, 7 },
                { 5, -7, 7 },
                { 6, -7, 7 },
                { 7, -7, 7 },
            },
        },
        {
            name = "concrete",
            correct = true,
            tiles = runs.expand {
                { -5, -5, 5 },
                { -4, -5, 5 },
                { -3, -5, 5 },
                { -2, -5, 5 },
                { -1, -5, 5 },
                { 0, -5, 5 },
                { 1, -5, 5 },
                { 2, -5, 5 },
                { 3, -5, 5 },
                { 4, -5, 5 },
                { 5, -5, 5 },
            },
        },
        {
            name = "refined-hazard-concrete-left",
            correct = true,
            tiles = runs.expand {
                { -4, -4, 4 },
                { -3, -4, 4 },
                { -2, -4, 4 },
                { -1, -4, 4 },
                { 0, -4, 4 },
                { 1, -4, 4 },
                { 2, -4, 4 },
                { 3, -4, 4 },
                { 4, -4, 4 },
            },
        },
    },
    entities = {
        { name = "otc-platform-wall", position = { -6.5, -6.5 } },
        { name = "otc-platform-wall", position = { 7.5, -6.5 } },
        { name = "otc-platform-wall", position = { -6.5, -5.5 } },
        { name = "otc-platform-wall", position = { 7.5, -5.5 } },
        { name = "otc-platform-wall", position = { -6.5, -4.5 } },
        { name = "otc-platform-wall", position = { 7.5, -4.5 } },
        { name = "otc-platform-wall", position = { -6.5, -3.5 } },
        { name = "otc-platform-wall", position = { 7.5, -3.5 } },
        { name = "otc-platform-wall", position = { -6.5, -2.5 } },
        { name = "otc-platform-wall", position = { 7.5, -2.5 } },
        { name = "otc-platform-wall", position = { -6.5, -1.5 } },
        { name = "otc-platform-wall", position = { 7.5, -1.5 } },
        { name = "otc-platform-wall", position = { -6.5, -0.5 } },
        { name = "otc-platform-wall", position = { 7.5, -0.5 } },
        { name = "otc-platform-wall", position = { 7.5, 0.5 } },
        { name = "otc-platform-wall", position = { -6.5, 1.5 } },
        { name = "otc-platform-wall", position = { 7.5, 1.5 } },
        { name = "otc-platform-wall", position = { -6.5, 2.5 } },
        { name = "otc-platform-wall", position = { 7.5, 2.5 } },
        { name = "otc-platform-wall", position = { -6.5, 3.5 } },
        { name = "otc-platform-wall", position = { 7.5, 3.5 } },
        { name = "otc-platform-wall", position = { -6.5, 4.5 } },
        { name = "otc-platform-wall", position = { 7.5, 4.5 } },
        { name = "otc-platform-wall", position = { -6.5, 5.5 } },
        { name = "otc-platform-wall", position = { 7.5, 5.5 } },
        { name = "otc-platform-wall", position = { -6.5, 6.5 } },
        { name = "otc-platform-wall", position = { 7.5, 6.5 } },
        { name = "otc-platform-wall", position = { -6.5, 7.5 } },
        { name = "otc-platform-wall", position = { 7.5, 7.5 } },
        { name = "otc-platform-wall", position = { -5.5, -6.5 } },
        { name = "otc-platform-wall", position = { -5.5, 7.5 } },
        { name = "otc-platform-wall", position = { -4.5, -6.5 } },
        { name = "otc-platform-wall", position = { -4.5, 7.5 } },
        { name = "otc-platform-wall", position = { -3.5, -6.5 } },
        { name = "otc-platform-wall", position = { -3.5, 7.5 } },
        { name = "otc-platform-wall", position = { -2.5, -6.5 } },
        { name = "otc-platform-wall", position = { -2.5, 7.5 } },
        { name = "otc-platform-wall", position = { -1.5, -6.5 } },
        { name = "otc-platform-wall", position = { -1.5, 7.5 } },
        { name = "otc-platform-wall", position = { -0.5, -6.5 } },
        { name = "otc-platform-wall", position = { -0.5, 7.5 } },
        { name = "otc-platform-wall", position = { 0.5, -6.5 } },
        { name = "otc-platform-wall", position = { 0.5, 7.5 } },
        { name = "otc-platform-wall", position = { 1.5, -6.5 } },
        { name = "otc-platform-wall", position = { 1.5, 7.5 } },
        { name = "otc-platform-wall", position = { 2.5, -6.5 } },
        { name = "otc-platform-wall", position = { 2.5, 7.5 } },
        { name = "otc-platform-wall", position = { 3.5, -6.5 } },
        { name = "otc-platform-wall", position = { 3.5, 7.5 } },
        { name = "otc-platform-wall", position = { 4.5, -6.5 } },
        { name = "otc-platform-wall", position = { 4.5, 7.5 } },
        { name = "otc-platform-wall", position = { 5.5, -6.5 } },
        { name = "otc-platform-wall", position = { 5.5, 7.5 } },
        { name = "otc-platform-wall", position = { 6.5, -6.5 } },
        { name = "otc-platform-wall", position = { 6.5, 7.5 } },
        { name = "gate", position = { -6.5, 0.5 }, role = "gate", side = "west", skip_create = true },
        { name = "rocket-silo", position = { 0.5, 0.5 }, role = "silo" },
        { name = "otc-teleporter", position = { -4.5, 0.5 }, direction = 0, role = "teleporter", skip_create = true },
    },
}
