-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape red_flask_factory
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "red_flask_factory",
    hook = "stock_belts",
    clearance_box = { { 0, 0 }, { 21, 13 } },
    tile_layers = {
        {
            name = "refined-concrete",
            correct = true,
            tiles = runs.expand {
                { 2, 2, 19 },
                { 3, 2, 19 },
                { 4, 2, 19 },
                { 5, 2, 17 },
                { 5, 19, 19 },
                { 6, 2, 17 },
                { 6, 19, 19 },
                { 7, 2, 19 },
                { 8, 2, 19 },
                { 9, 2, 19 },
                { 10, 2, 19 },
                { 11, 2, 19 },
            },
        },
        {
            name = "refined-hazard-concrete-left",
            correct = true,
            tiles = runs.expand {
                { 1, 1, 20 },
                { 2, 1, 1 },
                { 2, 20, 20 },
                { 3, 1, 1 },
                { 3, 20, 20 },
                { 4, 1, 1 },
                { 4, 20, 20 },
                { 5, 1, 1 },
                { 5, 20, 20 },
                { 6, 1, 1 },
                { 6, 20, 20 },
                { 7, 1, 1 },
                { 7, 20, 20 },
                { 8, 1, 1 },
                { 8, 20, 20 },
                { 9, 1, 1 },
                { 9, 20, 20 },
                { 10, 1, 1 },
                { 10, 20, 20 },
                { 11, 1, 1 },
                { 11, 20, 20 },
                { 12, 1, 20 },
            },
        },
    },
    entities = {
        { name = "assembling-machine-1", position = { 3.5, 3.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 6.5, 3.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 9.5, 3.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 12.5, 3.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 15.5, 3.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 18.5, 3.5 }, recipe = "iron-gear-wheel" },
        { name = "inserter", position = { 3.5, 5.5 }, direction = 8 },
        { name = "long-handed-inserter", position = { 4.5, 5.5 } },
        { name = "long-handed-inserter", position = { 5.5, 5.5 } },
        { name = "inserter", position = { 7.5, 5.5 }, direction = 8 },
        { name = "inserter", position = { 8.5, 5.5 }, direction = 8 },
        { name = "long-handed-inserter", position = { 10.5, 5.5 } },
        { name = "long-handed-inserter", position = { 11.5, 5.5 } },
        { name = "inserter", position = { 13.5, 5.5 }, direction = 8 },
        { name = "inserter", position = { 14.5, 5.5 }, direction = 8 },
        { name = "fast-inserter", position = { 17.5, 5.5 } },
        { name = "long-handed-inserter", position = { 16.5, 5.5 } },
        { name = "fast-inserter", position = { 18.5, 5.5 }, direction = 8 },
        { name = "transport-belt", position = { 3.5, 7.5 }, direction = 4 },
        { name = "substation", position = { 2, 7 } },
        { name = "transport-belt", position = { 3.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 4.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 5.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 5.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 4.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 6.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 7.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 7.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 6.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 8.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 9.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 9.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 8.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 10.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 11.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 11.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 10.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 12.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 13.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 13.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 12.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 14.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 15.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 15.5, 6.5 }, direction = 12 },
        { name = "transport-belt", position = { 14.5, 6.5 }, direction = 12 },
        -- Faces west, so transport line 2 is the top lane: copper is fed there
        -- and the bottom lane is left clear for the gear assembler's output.
        {
            name = "otc-supply-belt",
            position = { 17.5, 6.5 },
            direction = 12,
            role = "supply",
            belt_type = "output",
            item_right = "copper-plate",
        },
        { name = "transport-belt", position = { 16.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 17.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 16.5, 6.5 }, direction = 12 },
        {
            name = "otc-supply-belt",
            position = { 18.5, 6.5 },
            role = "supply",
            belt_type = "output",
            item_left = "iron-plate",
            item_right = "iron-plate",
        },
        {
            name = "otc-intake-belt",
            position = { 18.5, 7.5 },
            direction = 4,
            role = "intake",
            belt_type = "input",
        },
        { name = "substation", position = { 20, 7 } },
        { name = "long-handed-inserter", position = { 3.5, 8.5 } },
        { name = "inserter", position = { 4.5, 8.5 }, direction = 8 },
        { name = "inserter", position = { 5.5, 8.5 }, direction = 8 },
        { name = "long-handed-inserter", position = { 7.5, 8.5 } },
        { name = "long-handed-inserter", position = { 8.5, 8.5 } },
        { name = "inserter", position = { 10.5, 8.5 }, direction = 8 },
        { name = "inserter", position = { 11.5, 8.5 }, direction = 8 },
        { name = "long-handed-inserter", position = { 13.5, 8.5 } },
        { name = "long-handed-inserter", position = { 14.5, 8.5 } },
        { name = "inserter", position = { 16.5, 8.5 }, direction = 8 },
        { name = "assembling-machine-1", position = { 3.5, 10.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 6.5, 10.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 9.5, 10.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 12.5, 10.5 }, recipe = "automation-science-pack" },
        { name = "assembling-machine-1", position = { 15.5, 10.5 }, recipe = "automation-science-pack" },
    },
    notes = {
        "Captured from nauvis at origin -26,10.",
        "Fixed Nauvis build, not a gate expansion, so it needs no connection anchor.",
        "The intake belt's role was re-added by hand: the re-capture lost its tag.",
        "The sand and dirt the capture picked up were dropped: the concrete floor",
        "and its hazard border are the shape, and the ground round them is the",
        "district's grass. A re-capture will pick the sand back up -- drop it again.",
    },
}
