-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape solar_field tiles=none
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
return {
    format = 1,
    name = "solar_field",
    clearance_box = { { 0, 0 }, { 17, 17 } },
    entities = {
        { name = "solar-panel", position = { 1.5, 1.5 } },
        { name = "solar-panel", position = { 4.5, 1.5 } },
        { name = "solar-panel", position = { 7.5, 1.5 } },
        { name = "solar-panel", position = { 10.5, 1.5 } },
        { name = "solar-panel", position = { 13.5, 1.5 } },
        { name = "solar-panel", position = { 16.5, 1.5 } },
        { name = "solar-panel", position = { 1.5, 4.5 } },
        { name = "solar-panel", position = { 4.5, 4.5 } },
        { name = "solar-panel", position = { 7.5, 4.5 } },
        { name = "solar-panel", position = { 10.5, 4.5 } },
        { name = "solar-panel", position = { 13.5, 4.5 } },
        { name = "solar-panel", position = { 16.5, 4.5 } },
        { name = "solar-panel", position = { 1.5, 7.5 } },
        { name = "solar-panel", position = { 4.5, 7.5 } },
        { name = "accumulator", position = { 7, 7 } },
        { name = "accumulator", position = { 9, 7 } },
        { name = "accumulator", position = { 11, 7 } },
        { name = "solar-panel", position = { 13.5, 7.5 } },
        { name = "solar-panel", position = { 16.5, 7.5 } },
        { name = "accumulator", position = { 7, 9 } },
        { name = "substation", position = { 9, 9 } },
        { name = "accumulator", position = { 11, 9 } },
        { name = "solar-panel", position = { 1.5, 10.5 } },
        { name = "solar-panel", position = { 4.5, 10.5 } },
        { name = "accumulator", position = { 7, 11 } },
        { name = "accumulator", position = { 9, 11 } },
        { name = "accumulator", position = { 11, 11 } },
        { name = "solar-panel", position = { 13.5, 10.5 } },
        { name = "solar-panel", position = { 16.5, 10.5 } },
        { name = "solar-panel", position = { 1.5, 13.5 } },
        { name = "solar-panel", position = { 4.5, 13.5 } },
        { name = "solar-panel", position = { 7.5, 13.5 } },
        { name = "solar-panel", position = { 10.5, 13.5 } },
        { name = "solar-panel", position = { 13.5, 13.5 } },
        { name = "solar-panel", position = { 16.5, 13.5 } },
        { name = "solar-panel", position = { 1.5, 16.5 } },
        { name = "solar-panel", position = { 4.5, 16.5 } },
        { name = "solar-panel", position = { 7.5, 16.5 } },
        { name = "solar-panel", position = { 10.5, 16.5 } },
        { name = "solar-panel", position = { 13.5, 16.5 } },
        { name = "solar-panel", position = { 16.5, 16.5 } },
    },
    notes = {
        "Captured from nauvis at origin -46,18, entities only -- the field lays no tiles.",
    },
}
