-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape station_interior
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "station_interior",
    hook = "station_interior",
    destroy_decoratives = false,
    clearance_box = { { -11, -11 }, { 11, 11 } },
    tile_layers = {
        {
            name = "otc-platform",
            correct = false,
            tiles = runs.expand {
                { -10, -10, 10 },
                { -9, -10, 10 },
                { -8, -10, 10 },
                { -7, -10, 10 },
                { -6, -10, 10 },
                { -5, -10, 10 },
                { -4, -10, 10 },
                { -3, -10, 10 },
                { -2, -10, 10 },
                { -1, -10, 10 },
                { 0, -10, 10 },
                { 1, -10, 10 },
                { 2, -10, 10 },
                { 3, -10, 10 },
                { 4, -10, 10 },
                { 5, -10, 10 },
                { 6, -10, 10 },
                { 7, -10, 10 },
                { 8, -10, 10 },
                { 9, -10, 10 },
                { 10, -10, 10 },
            },
        },
        {
            name = "refined-concrete",
            correct = false,
            tiles = runs.expand {
                { -11, -1, 1 },
                { -1, -11, -11 },
                { -1, 11, 11 },
                { 0, -11, -11 },
                { 0, 11, 11 },
                { 1, -11, -11 },
                { 1, 11, 11 },
                { 11, -1, 1 },
            },
        },
        {
            name = "concrete",
            correct = false,
            tiles = runs.expand {
                { -5, -5, 5 },
                { -4, -5, 5 },
                { -3, -5, 5 },
                { -2, -5, 5 },
                { -1, -5, 5 },
                { 0, -5, 5 },
                { 1, -5, 5 },
                { 2, -5, 5 },
                { 3, -5, 5 },
                { 4, -5, 5 },
                { 5, -5, 5 },
            },
        },
        {
            name = "refined-hazard-concrete-left",
            correct = false,
            tiles = runs.expand {
                { -4, -4, 4 },
                { -3, -4, 4 },
                { -2, -4, 4 },
                { -1, -4, 4 },
                { 0, -4, 4 },
                { 1, -4, 4 },
                { 2, -4, 4 },
                { 3, -4, 4 },
                { 4, -4, 4 },
            },
        },
    },
    entities = {
        { name = "otc-platform-wall", position = { -9.5, -9.5 } },
        { name = "otc-platform-wall", position = { -9.5, -8.5 } },
        { name = "otc-platform-wall", position = { -9.5, -7.5 } },
        { name = "otc-platform-wall", position = { -9.5, -6.5 } },
        { name = "otc-platform-wall", position = { -9.5, -5.5 } },
        { name = "otc-platform-wall", position = { -9.5, -4.5 } },
        { name = "otc-platform-wall", position = { -9.5, -3.5 } },
        { name = "otc-platform-wall", position = { -9.5, -2.5 } },
        { name = "otc-platform-wall", position = { -9.5, -1.5 } },
        { name = "otc-platform-wall", position = { -9.5, -0.5 } },
        { name = "otc-platform-wall", position = { -9.5, 1.5 } },
        { name = "otc-platform-wall", position = { -9.5, 2.5 } },
        { name = "otc-platform-wall", position = { -9.5, 3.5 } },
        { name = "otc-platform-wall", position = { -9.5, 4.5 } },
        { name = "otc-platform-wall", position = { -9.5, 5.5 } },
        { name = "otc-platform-wall", position = { -9.5, 6.5 } },
        { name = "otc-platform-wall", position = { -9.5, 7.5 } },
        { name = "otc-platform-wall", position = { -9.5, 8.5 } },
        { name = "otc-platform-wall", position = { -9.5, 9.5 } },
        { name = "otc-platform-wall", position = { -9.5, 10.5 } },
        { name = "otc-platform-wall", position = { 10.5, -9.5 } },
        { name = "otc-platform-wall", position = { 10.5, -8.5 } },
        { name = "otc-platform-wall", position = { 10.5, -7.5 } },
        { name = "otc-platform-wall", position = { 10.5, -6.5 } },
        { name = "otc-platform-wall", position = { 10.5, -5.5 } },
        { name = "otc-platform-wall", position = { 10.5, -4.5 } },
        { name = "otc-platform-wall", position = { 10.5, -3.5 } },
        { name = "otc-platform-wall", position = { 10.5, -2.5 } },
        { name = "otc-platform-wall", position = { 10.5, -1.5 } },
        { name = "otc-platform-wall", position = { 10.5, -0.5 } },
        { name = "otc-platform-wall", position = { 10.5, 1.5 } },
        { name = "otc-platform-wall", position = { 10.5, 2.5 } },
        { name = "otc-platform-wall", position = { 10.5, 3.5 } },
        { name = "otc-platform-wall", position = { 10.5, 4.5 } },
        { name = "otc-platform-wall", position = { 10.5, 5.5 } },
        { name = "otc-platform-wall", position = { 10.5, 6.5 } },
        { name = "otc-platform-wall", position = { 10.5, 7.5 } },
        { name = "otc-platform-wall", position = { 10.5, 8.5 } },
        { name = "otc-platform-wall", position = { 10.5, 9.5 } },
        { name = "otc-platform-wall", position = { 10.5, 10.5 } },
        { name = "otc-platform-wall", position = { -8.5, -9.5 } },
        { name = "otc-platform-wall", position = { -7.5, -9.5 } },
        { name = "otc-platform-wall", position = { -6.5, -9.5 } },
        { name = "otc-platform-wall", position = { -5.5, -9.5 } },
        { name = "otc-platform-wall", position = { -4.5, -9.5 } },
        { name = "otc-platform-wall", position = { -3.5, -9.5 } },
        { name = "otc-platform-wall", position = { -2.5, -9.5 } },
        { name = "otc-platform-wall", position = { -1.5, -9.5 } },
        { name = "otc-platform-wall", position = { -0.5, -9.5 } },
        { name = "otc-platform-wall", position = { 1.5, -9.5 } },
        { name = "otc-platform-wall", position = { 2.5, -9.5 } },
        { name = "otc-platform-wall", position = { 3.5, -9.5 } },
        { name = "otc-platform-wall", position = { 4.5, -9.5 } },
        { name = "otc-platform-wall", position = { 5.5, -9.5 } },
        { name = "otc-platform-wall", position = { 6.5, -9.5 } },
        { name = "otc-platform-wall", position = { 7.5, -9.5 } },
        { name = "otc-platform-wall", position = { 8.5, -9.5 } },
        { name = "otc-platform-wall", position = { 9.5, -9.5 } },
        { name = "otc-platform-wall", position = { -8.5, 10.5 } },
        { name = "otc-platform-wall", position = { -7.5, 10.5 } },
        { name = "otc-platform-wall", position = { -6.5, 10.5 } },
        { name = "otc-platform-wall", position = { -5.5, 10.5 } },
        { name = "otc-platform-wall", position = { -4.5, 10.5 } },
        { name = "otc-platform-wall", position = { -3.5, 10.5 } },
        { name = "otc-platform-wall", position = { -2.5, 10.5 } },
        { name = "otc-platform-wall", position = { -1.5, 10.5 } },
        { name = "otc-platform-wall", position = { -0.5, 10.5 } },
        { name = "otc-platform-wall", position = { 1.5, 10.5 } },
        { name = "otc-platform-wall", position = { 2.5, 10.5 } },
        { name = "otc-platform-wall", position = { 3.5, 10.5 } },
        { name = "otc-platform-wall", position = { 4.5, 10.5 } },
        { name = "otc-platform-wall", position = { 5.5, 10.5 } },
        { name = "otc-platform-wall", position = { 6.5, 10.5 } },
        { name = "otc-platform-wall", position = { 7.5, 10.5 } },
        { name = "otc-platform-wall", position = { 8.5, 10.5 } },
        { name = "otc-platform-wall", position = { 9.5, 10.5 } },
        { name = "otc-platform-wall", position = { -0.5, -10.5 } },
        { name = "otc-platform-wall", position = { 1.5, -10.5 } },
        { name = "otc-platform-wall", position = { -0.5, 11.5 } },
        { name = "otc-platform-wall", position = { 1.5, 11.5 } },
        { name = "otc-platform-wall", position = { -10.5, -0.5 } },
        { name = "otc-platform-wall", position = { -10.5, 1.5 } },
        { name = "otc-platform-wall", position = { 11.5, -0.5 } },
        { name = "otc-platform-wall", position = { 11.5, 1.5 } },
        { name = "gate", position = { 10.5, 0.5 }, role = "gate", side = "east", skip_create = true },
        {
            name = "otc-gate-computer",
            position = { 11.5, 0.5 },
            role = "computer",
            side = "east",
            skip_create = true,
        },
        { name = "gate", position = { -9.5, 0.5 }, role = "gate", side = "west", skip_create = true },
        {
            name = "otc-gate-computer",
            position = { -10.5, 0.5 },
            role = "computer",
            side = "west",
            skip_create = true,
        },
        { name = "gate", position = { 0.5, 10.5 }, role = "gate", side = "north", skip_create = true },
        {
            name = "otc-gate-computer",
            position = { 0.5, 11.5 },
            role = "computer",
            side = "north",
            skip_create = true,
        },
        { name = "gate", position = { 0.5, -9.5 }, role = "gate", side = "south", skip_create = true },
        {
            name = "otc-gate-computer",
            position = { 0.5, -10.5 },
            role = "computer",
            side = "south",
            skip_create = true,
        },
        { name = "otc-trading-silo", position = { 0.5, 0.5 }, role = "silo" },
        {
            name = "otc-teleporter",
            position = { 0.5, 5.5 },
            direction = 12,
            role = "return_teleporter",
            skip_create = true,
        },
    },
    anchors = {
        ["arrival"] = { position = { x = 0, y = 6 } },
    },
}
