-- Shape definition captured from the game.
-- Re-capture in game with: /otc-capture-shape stone_mine
-- Coordinates are shape-local; the canonical orientation is a gate on the
-- west edge with the room extending east. See README.md "Capturing shapes".
local runs = require("scripts.shape_runs")

return {
    format = 1,
    name = "stone_mine",
    hook = "stock_belts",
    clearance_box = { { 0, 0 }, { 8, 9 } },
    tile_layers = {
        {
            name = "grass-2",
            correct = true,
            tiles = runs.expand {
                { 0, 5, 8 },
                { 1, 5, 8 },
                { 2, 0, 1 },
                { 2, 4, 8 },
                { 3, 0, 8 },
                { 4, 0, 7 },
                { 5, 0, 7 },
                { 6, 0, 6 },
                { 7, 0, 5 },
                { 8, 0, 4 },
                { 9, 0, 4 },
            },
        },
        {
            name = "grass-4",
            correct = true,
            tiles = runs.expand {
                { 0, 0, 4 },
                { 1, 0, 4 },
                { 2, 2, 3 },
            },
        },
        {
            name = "red-desert-0",
            correct = true,
            tiles = runs.expand {
                { 4, 8, 8 },
                { 5, 8, 8 },
                { 6, 7, 8 },
                { 7, 6, 8 },
                { 8, 5, 8 },
                { 9, 5, 8 },
            },
        },
    },
    entities = {
        { name = "substation", position = { 5, 1 } },
        { name = "electric-mining-drill", position = { 2.5, 3.5 }, direction = 4 },
        { name = "transport-belt", position = { 4.5, 4.5 }, direction = 8 },
        { name = "transport-belt", position = { 4.5, 3.5 }, direction = 8 },
        { name = "electric-mining-drill", position = { 6.5, 3.5 }, direction = 12 },
        { name = "transport-belt", position = { 4.5, 6.5 }, direction = 8 },
        { name = "transport-belt", position = { 4.5, 5.5 }, direction = 8 },
        { name = "electric-mining-drill", position = { 2.5, 7.5 }, direction = 4 },
        { name = "transport-belt", position = { 4.5, 8.5 }, direction = 8 },
        { name = "transport-belt", position = { 4.5, 7.5 }, direction = 8 },
        { name = "electric-mining-drill", position = { 6.5, 7.5 }, direction = 12 },
        { name = "otc-intake-belt", position = { 4.5, 9.5 }, direction = 8, role = "intake", belt_type = "input" },
    },
    resources = {
        { name = "stone", position = { 2, 2 }, amount = 208050 },
        { name = "stone", position = { 4, 2 }, amount = 208040 },
        { name = "stone", position = { 3, 2 }, amount = 208050 },
        { name = "stone", position = { 4, 1 }, amount = 208040 },
        { name = "stone", position = { 6, 2 }, amount = 208050 },
        { name = "stone", position = { 5, 2 }, amount = 208050 },
        { name = "stone", position = { 2, 4 }, amount = 208050 },
        { name = "stone", position = { 1, 4 }, amount = 208050 },
        { name = "stone", position = { 2, 3 }, amount = 208050 },
        { name = "stone", position = { 1, 3 }, amount = 208050 },
        { name = "stone", position = { 4, 4 }, amount = 208050 },
        { name = "stone", position = { 3, 4 }, amount = 208050 },
        { name = "stone", position = { 4, 3 }, amount = 208050 },
        { name = "stone", position = { 3, 3 }, amount = 208050 },
        { name = "stone", position = { 6, 4 }, amount = 208050 },
        { name = "stone", position = { 5, 4 }, amount = 208050 },
        { name = "stone", position = { 6, 3 }, amount = 208050 },
        { name = "stone", position = { 5, 3 }, amount = 208050 },
        { name = "stone", position = { 7, 4 }, amount = 208050 },
        { name = "stone", position = { 7, 3 }, amount = 208050 },
        { name = "stone", position = { 0, 5 }, amount = 208050 },
        { name = "stone", position = { 2, 6 }, amount = 208044 },
        { name = "stone", position = { 1, 6 }, amount = 208050 },
        { name = "stone", position = { 2, 5 }, amount = 208050 },
        { name = "stone", position = { 1, 5 }, amount = 208050 },
        { name = "stone", position = { 4, 6 }, amount = 208050 },
        { name = "stone", position = { 3, 6 }, amount = 208050 },
        { name = "stone", position = { 4, 5 }, amount = 208044 },
        { name = "stone", position = { 3, 5 }, amount = 208050 },
        { name = "stone", position = { 6, 6 }, amount = 208050 },
        { name = "stone", position = { 5, 6 }, amount = 208050 },
        { name = "stone", position = { 6, 5 }, amount = 208050 },
        { name = "stone", position = { 5, 5 }, amount = 208050 },
        { name = "stone", position = { 7, 6 }, amount = 208050 },
        { name = "stone", position = { 8, 5 }, amount = 208050 },
        { name = "stone", position = { 7, 5 }, amount = 208050 },
        { name = "stone", position = { 2, 8 }, amount = 208050 },
        { name = "stone", position = { 2, 7 }, amount = 208050 },
        { name = "stone", position = { 1, 7 }, amount = 208050 },
        { name = "stone", position = { 4, 8 }, amount = 208050 },
        { name = "stone", position = { 3, 8 }, amount = 208050 },
        { name = "stone", position = { 4, 7 }, amount = 208050 },
        { name = "stone", position = { 3, 7 }, amount = 208050 },
        { name = "stone", position = { 6, 8 }, amount = 208050 },
        { name = "stone", position = { 5, 8 }, amount = 208050 },
        { name = "stone", position = { 6, 7 }, amount = 208050 },
        { name = "stone", position = { 5, 7 }, amount = 208050 },
        { name = "stone", position = { 7, 7 }, amount = 208050 },
        { name = "stone", position = { 4, 9 }, amount = 208050 },
    },
    notes = {
        "Captured from nauvis at origin -77,-5. Placed, not bought, so it has no",
        "connection anchor; nauvis_industry lists it in MINE_BLOCKS.",
        "role=intake belts are registered as stock intakes by the hook.",
        "No generation of its own: the substation draws off the coal block's grid.",
    },
}
