return {
    {
        type = "tile",
        name = "otc-platform",
        order = "a-a-a",
        collision_mask = {layers = {ground_tile = true}},
        walking_speed_modifier = 1.5,
        layer = 17,
        layer_group = "ground-artificial",
        transition_overlay_layer_offset = 2,
        decorative_removal_probability = 0.25,
        variants = {
            transition = {
                overlay_layout = {
                    inner_corner = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-inner-corner.png",
                        count = 16,
                        scale = 0.5,
                    },
                    outer_corner = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-outer-corner.png",
                        count = 8,
                        scale = 0.5,
                    },
                    side = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-side.png",
                        count = 16,
                        scale = 0.5,
                    },
                    u_transition = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-u.png",
                        count = 8,
                        scale = 0.5,
                    },
                    o_transition = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-o.png",
                        count = 4,
                        scale = 0.5,
                    },
                },
                mask_layout = {
                    inner_corner = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-inner-corner-mask.png",
                        count = 16,
                        scale = 0.5,
                    },
                    outer_corner = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-outer-corner-mask.png",
                        count = 8,
                        scale = 0.5,
                    },
                    side = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-side-mask.png",
                        count = 16,
                        scale = 0.5,
                    },
                    u_transition = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-u-mask.png",
                        count = 8,
                        scale = 0.5,
                    },
                    o_transition = {
                        spritesheet = "__base__/graphics/terrain/concrete/concrete-o-mask.png",
                        count = 4,
                        scale = 0.5,
                    },
                },
            },
            material_background = {
                picture = "__base__/graphics/terrain/concrete/refined-concrete.png",
                count = 8,
                scale = 0.5,
            },
        },
        transitions = {
            {
                to_tiles = {"out-of-map"},
                transition_group = 2,
                background_layer_offset = 1,
                background_layer_group = "zero",
                offset_background_layer_by_tile_layer = true,
                spritesheet = "__base__/graphics/terrain/out-of-map-transition/concrete-out-of-map-transition.png",
                layout = {
                    scale = 0.5,
                    inner_corner_count = 4,
                    outer_corner_count = 4,
                    side_count = 8,
                    u_transition_count = 1,
                    o_transition_count = 1,
                    inner_corner_y = 0,
                    outer_corner_y = 576,
                    side_y = 1152,
                    u_transition_y = 1728,
                    o_transition_y = 2304,
                    inner_corner_tile_height = 2,
                    outer_corner_tile_height = 2,
                    side_tile_height = 2,
                    u_transition_tile_height = 2,
                    o_transition_tile_height = 2,
                    overlay = {x_offset = 0},
                    mask = {x_offset = 2176},
                    background = {x_offset = 1088},
                },
            },
        },
        map_color = {49, 48, 45},
        scorch_mark_color = {r = 0.373, g = 0.307, b = 0.243, a = 1.000},
        vehicle_friction_modifier = 0.8,
    },
    {
        type = "wall",
        name = "otc-platform-wall",
        icon = "__base__/graphics/icons/wall.png",
        icon_size = 64,
        flags = {"placeable-neutral", "player-creation"},
        collision_box = {{-0.29, -0.29}, {0.29, 0.29}},
        selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
        max_health = 1000,
        repair_speed_modifier = 2,
        corpse = "wall-remnants",
        dying_explosion = "wall-explosion",
        impact_category = "stone",
        visual_merge_group = 0,
        damaged_trigger_effect = {
            type = "create-entity",
            entity_name = "rock-damaged-explosion",
            trigger_created_entity = true,
        },
        resistances = {
            {type = "physical", decrease = 3, percent = 20},
            {type = "impact", decrease = 45, percent = 60},
            {type = "explosion", decrease = 10, percent = 30},
            {type = "fire", percent = 100},
            {type = "acid", percent = 80},
            {type = "laser", percent = 70},
        },
        pictures = {
            single = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-single.png",
                        priority = "extra-high",
                        width = 64,
                        height = 86,
                        variation_count = 2,
                        line_length = 2,
                        shift = util.by_pixel(0, -5),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-single-shadow.png",
                        priority = "extra-high",
                        width = 98,
                        height = 60,
                        repeat_count = 2,
                        shift = util.by_pixel(10, 17),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            straight_vertical = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-vertical.png",
                        priority = "extra-high",
                        width = 64,
                        height = 134,
                        variation_count = 5,
                        line_length = 5,
                        shift = util.by_pixel(0, 8),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-vertical-shadow.png",
                        priority = "extra-high",
                        width = 98,
                        height = 110,
                        repeat_count = 5,
                        shift = util.by_pixel(10, 29),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            straight_horizontal = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-horizontal.png",
                        priority = "extra-high",
                        width = 64,
                        height = 92,
                        variation_count = 6,
                        line_length = 6,
                        shift = util.by_pixel(0, -2),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-horizontal-shadow.png",
                        priority = "extra-high",
                        width = 124,
                        height = 68,
                        repeat_count = 6,
                        shift = util.by_pixel(14, 15),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            corner_right_down = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-corner-right.png",
                        priority = "extra-high",
                        width = 64,
                        height = 128,
                        variation_count = 2,
                        line_length = 2,
                        shift = util.by_pixel(0, 7),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-corner-right-shadow.png",
                        priority = "extra-high",
                        width = 124,
                        height = 120,
                        repeat_count = 2,
                        shift = util.by_pixel(17, 28),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            corner_left_down = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-corner-left.png",
                        priority = "extra-high",
                        width = 64,
                        height = 134,
                        variation_count = 2,
                        line_length = 2,
                        shift = util.by_pixel(0, 7),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-corner-left-shadow.png",
                        priority = "extra-high",
                        width = 102,
                        height = 120,
                        repeat_count = 2,
                        shift = util.by_pixel(9, 28),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            t_up = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-t.png",
                        priority = "extra-high",
                        width = 64,
                        height = 134,
                        variation_count = 4,
                        line_length = 4,
                        shift = util.by_pixel(0, 7),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-t-shadow.png",
                        priority = "extra-high",
                        width = 124,
                        height = 120,
                        repeat_count = 4,
                        shift = util.by_pixel(14, 28),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            ending_right = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-ending-right.png",
                        priority = "extra-high",
                        width = 64,
                        height = 92,
                        variation_count = 2,
                        line_length = 2,
                        shift = util.by_pixel(0, -3),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-ending-right-shadow.png",
                        priority = "extra-high",
                        width = 124,
                        height = 68,
                        repeat_count = 2,
                        shift = util.by_pixel(17, 15),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            ending_left = {
                layers = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-ending-left.png",
                        priority = "extra-high",
                        width = 64,
                        height = 92,
                        variation_count = 2,
                        line_length = 2,
                        shift = util.by_pixel(0, -3),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-ending-left-shadow.png",
                        priority = "extra-high",
                        width = 102,
                        height = 68,
                        repeat_count = 2,
                        shift = util.by_pixel(9, 15),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            filling = {
                filename = "__base__/graphics/entity/wall/wall-filling.png",
                priority = "extra-high",
                width = 48,
                height = 56,
                variation_count = 8,
                line_length = 8,
                shift = util.by_pixel(0, -1),
                scale = 0.5,
            },
            water_connection_patch = {
                sheets = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-patch.png",
                        priority = "extra-high",
                        width = 116,
                        height = 128,
                        shift = util.by_pixel(0, -2),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-patch-shadow.png",
                        priority = "extra-high",
                        width = 144,
                        height = 100,
                        shift = util.by_pixel(9, 15),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
            gate_connection_patch = {
                sheets = {
                    {
                        filename = "__base__/graphics/entity/wall/wall-gate.png",
                        priority = "extra-high",
                        width = 82,
                        height = 108,
                        shift = util.by_pixel(0, -7),
                        scale = 0.5,
                    },
                    {
                        filename = "__base__/graphics/entity/wall/wall-gate-shadow.png",
                        priority = "extra-high",
                        width = 130,
                        height = 78,
                        shift = util.by_pixel(14, 18),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
        },
        wall_diode_green = {
            sheet = {
                filename = "__base__/graphics/entity/wall/wall-diode-green.png",
                priority = "extra-high",
                width = 72,
                height = 44,
                draw_as_glow = true,
                shift = util.by_pixel(-1, -23),
                scale = 0.5,
            },
        },
        wall_diode_green_light_top = {
            minimum_darkness = 0.3,
            color = {g = 1},
            shift = util.by_pixel(0, -30),
            size = 1,
            intensity = 0.2,
        },
        wall_diode_green_light_right = {
            minimum_darkness = 0.3,
            color = {g = 1},
            shift = util.by_pixel(12, -23),
            size = 1,
            intensity = 0.2,
        },
        wall_diode_green_light_bottom = {
            minimum_darkness = 0.3,
            color = {g = 1},
            shift = util.by_pixel(0, -17),
            size = 1,
            intensity = 0.2,
        },
        wall_diode_green_light_left = {
            minimum_darkness = 0.3,
            color = {g = 1},
            shift = util.by_pixel(-12, -23),
            size = 1,
            intensity = 0.2,
        },
        wall_diode_red = {
            sheet = {
                filename = "__base__/graphics/entity/wall/wall-diode-red.png",
                priority = "extra-high",
                width = 72,
                height = 44,
                draw_as_glow = true,
                shift = util.by_pixel(-1, -23),
                scale = 0.5,
            },
        },
        wall_diode_red_light_top = {
            minimum_darkness = 0.3,
            color = {r = 1},
            shift = util.by_pixel(0, -30),
            size = 1,
            intensity = 0.2,
        },
        wall_diode_red_light_right = {
            minimum_darkness = 0.3,
            color = {r = 1},
            shift = util.by_pixel(12, -23),
            size = 1,
            intensity = 0.2,
        },
        wall_diode_red_light_bottom = {
            minimum_darkness = 0.3,
            color = {r = 1},
            shift = util.by_pixel(0, -17),
            size = 1,
            intensity = 0.2,
        },
        wall_diode_red_light_left = {
            minimum_darkness = 0.3,
            color = {r = 1},
            shift = util.by_pixel(-12, -23),
            size = 1,
            intensity = 0.2,
        },
    },
}
